### ISSUE TITLE
How to use pacman within travis?

### ISSUE THREAD

**Issue by vonpupp** [mikkeloscar/arch-travis#1]
Hello,

Congratulations on arch-travis, it looks very promising and I have a lot of enthusiasm to work with it even when I'm new to arch-travis. I'm trying to test my ansible playbook based on an arch host however when ansible tries to install something with pacman it doesn't work.

Herewith the Travis [log](https://travis-ci.org/vonpupp/ansible-role-vonpupp/builds/85029752). Note that when I do a `which bash` I get a 0 (success), however when I try `which pacman` I get a 1 (error).

Do you have any idea?

**Comment by mikkeloscar** [comment]
Hello, you are running those commands on the travis host instead of in the arch-travis chroot.

you need to add your commands under this script entry: https://github.com/vonpupp/ansible-role-vonpupp/blob/master/.travis.yml#L19

**Comment by vonpupp** [comment]
Thank you very much! My mistake, I apologize.
