### ISSUE TITLE
Support for tests requiring xvfb

### ISSUE THREAD

**Issue by elvisangelaccio** [mikkeloscar/arch-travis#14]
Hi. First of all, thanks for this tool, it is awesome.

I need to run a couple of unit tests (in a Qt codebase) that require a GUI, in other words a running Xorg server.
The tests currently fail with a `QXcbConnection: Could not connect to display` error. This is my travis config file: https://github.com/aelog/ark/blob/master/.travis.yml

I think using xvfb should do the trick. Travis does provide a [guide to run GUI tests](https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI). however we are inside a chroot, so I guess I need to setup xfvb _within_ the archlinux chroot, right? Any idea how to do so?

**Comment by elvisangelaccio** [comment]
Solved!

I just installed the `xorg-server-xvfb` archlinux package and then run the tests through the `xvfb-run` wrapper.
For the record: `xvfb-run --auto-servernum ctest --output-on-failure` where `ctest` is the actual command to run the tests.

**Comment by SunyataZero** [comment]
Hi all, i found this issue when searching for a solution to "QXcbConnection: Could not connect to display". I can see that you have solved the issue and i have looked at the current .travis.yml file but just wanted to share the solution that i am using (which is similar to your solution): https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI

Kind Regards, Tord
