### ISSUE TITLE
CMake out-of-source builds not working

### ISSUE THREAD

**Issue by elvisangelaccio** [mikkeloscar/arch-travis#15]
Hi,
in [my cmake project](https://github.com/aelog/ark/blob/master/.travis.yml) I can only do in-source builds, i.e. running the cmake command from the root folder of the project. This is also what sway does: https://github.com/SirCmpwn/sway/blob/master/.travis.yml#L22

Is there a reason why [out-of-source builds](https://cmake.org/Wiki/CMake_FAQ#What_is_an_.22out-of-source.22_build.3F) don't work? I tried with the following `arch.script`:

```
arch:
  script:
    - "mkdir build"
    - "cd build"
    - "cmake <OPTIONS> .."
    - "make"
```

but the build failed with the following error: 

```
$ cmake -DCMAKE_BUILD_TYPE=Debug -DKDE_INSTALL_LIBDIR=lib -DKDE_INSTALL_USE_QT_SYS_PATHS=ON -DCMAKE_INSTALL_PREFIX=/usr ..

CMake Error: The source directory "/home/travis/build/aelog" does not appear to contain CMakeLists.txt.
```

which seems to imply that the script could not change to working dir to `build`...

**Comment by mikkeloscar** [comment]
It's because `cd build` is a separate command and all commands are run from the base dir. So you need something like `cd build && cmake .. && make` or put it all in a script.

I'm pretty sure the `script` directive in travis works the same way.

**Comment by elvisangelaccio** [comment]
Thanks. Using a script sounds like a reasonable workaround, but after all I'm ok sticking with in-source builds, for now :)
