### ISSUE TITLE
Builds failing from this script

### ISSUE THREAD

**Issue by ddevault** [mikkeloscar/arch-travis#2]
https://travis-ci.org/SirCmpwn/sway/builds/90725639

**Comment by mikkeloscar** [comment]
Could you try to do a rebuild just to check if the server had temporary issues? If it still fails, then I'll look into it tonight!

**Comment by ddevault** [comment]
Well, looking at the error log, the fault is probably assigned here. I'll give it another go, though.

**Comment by ddevault** [comment]
Well, looks like it was a fluke. Thanks!

**Comment by mikkeloscar** [comment]
Yeah, it looked weird, and travis has been unstable from time to time. If you see it happening again just let me know then I can look further into it and see if the script could be causing the problems!
