### ISSUE TITLE
pacaur fails with "editor variable unset"

### ISSUE THREAD

**Issue by corngood** [mikkeloscar/arch-travis#21]
Sometime In the last week, arch-travis was broken by an update to pacaur, it will fail when executing pacaur with:

```
:: editor variable unset
```

You can work around it by setting `EDITOR=false` before calling arch-travis.sh.

**Comment by corngood** [comment]
Example of a failed build: https://travis-ci.org/corngood/archlinux-amdgpu/builds/198889952

**Comment by yuyichao** [comment]
Hitting the same issue in the past 2-3 days too. Seems that `pacaur` requires a valid editor setting even when it's not needed now?

**Comment by corngood** [comment]
It needs either `$VISUAL`, `$EDITOR` or `vi`.  I suppose that's reasonable, so the best fix is probably setting `EDITOR=false` in arch-travis.  If anyone really disagrees with the behaviour in pacaur, you could raise an issue over there.

**Comment by mikkeloscar** [comment]
Thanks for raising the issue, this should be fixed now.
