### ISSUE TITLE
ca-certificates-utils 20170307-1 upgrade requires manual intervention

### ISSUE THREAD

**Issue by meonwax** [mikkeloscar/arch-travis#23]
Please include this in `arch-travis.sh`:
https://www.archlinux.org/news/ca-certificates-utils-20170307-1-upgrade-requires-manual-intervention/

 I think when *2017.04.01* will be released, this workaround could be safely removed.

**Comment by mikkeloscar** [comment]
Thanks for reporting the issue!

**Comment by meonwax** [comment]
Thanks. Just tested and it works.
Be sure to remove the workaround when the new boostrap release is available.
