### ISSUE TITLE
umount errors: device is busy

### ISSUE THREAD

**Issue by meonwax** [mikkeloscar/arch-travis#26]
I use your chroot-environment to build my favourite AUR packages.
After the custom buildscript finishes, `arch-travis.sh` is trying to take down the chroot and unmounting the devices.
This fails for me:

    umount: /home/travis/root.x86_64/dev: device is busy.
            (In some cases useful info about processes that use
             the device is found by lsof(8) or fuser(1))
    umount: /home/travis/root.x86_64: device is busy.
            (In some cases useful info about processes that use
             the device is found by lsof(8) or fuser(1))
    rm: cannot remove `/home/travis/root.x86_64/dev/pts': Device or resource busy

Maybe we have to add a sleep or a lsof-waiting loop.

**Comment by ldenman** [comment]
I am seeing this as well @meonwax ; any solve?

**Comment by meonwax** [comment]
Not really. To be honest, i don't use this approach anymore as i'm doing my nightly builds within an chroot-environment on a Debian box i own.

But i assume this is a timing issue, so waiting a few seconds before leaving the chroot and unmounting could solve this.

**Comment by mikkeloscar** [comment]
Not a problem since switching to docker based build.
