### ISSUE TITLE
Default mirror is down

### ISSUE THREAD

**Issue by ddevault** [mikkeloscar/arch-travis#27]

**Comment by mikkeloscar** [comment]
Thanks!

Temp fix in e562abce98d71866e4335f3808ba158e29e271cb

Will see about implementing fallback mirrors later today: #18

**Comment by mikkeloscar** [comment]
Fixed in b92b088e

**Comment by ddevault** [comment]
This is hardly any better https://travis-ci.org/SirCmpwn/sway/jobs/224035904
