### ISSUE TITLE
Handling replaces/conflicts

### ISSUE THREAD

**Issue by jelly** [mikkeloscar/arch-travis#29]
I want to use pacman-git to test pyalpm-git in a travisci job, but of course paman-git conflicts with pacman, is there any way to say yes in this situations to resolve the conflict.

```
:: pacman-git and pacman are in conflict. Remove pacman? [y/N] 
error: unresolvable package conflicts detected
error: failed to prepare transaction (conflicting dependencies)
:: pacman-git and pacman are in conflict
```

**Comment by mikkeloscar** [comment]
It should work to do `yes | pacman -S...`. We could enable this feature through an environment variable e.g. `PACMAN_ALWAYS_YES`.

Would that work for you?

**Comment by jelly** [comment]
Ok, with ```yes | pacman -S``` works but you can't use it in **packages** so the env variable might be nicer.
