### ISSUE TITLE
yay linked against old pacman version

### ISSUE THREAD

**Issue by Teemperor** [mikkeloscar/arch-travis#47]
It seems the image (or at least `yay`) needs to be updated, because I get the following error messages lately:
```
yay: error while loading shared libraries: libalpm.so.10: cannot open shared object file: No such file or directory
yay: error while loading shared libraries: libalpm.so.10: cannot open shared object file: No such file or directory
yay: error while loading shared libraries: libalpm.so.10: cannot open shared object file: No such file or directory
```
[From](https://travis-ci.org/Teemperor/Nils/jobs/384943016)

**Comment by mikkeloscar** [comment]
Hi, sorry about this. The arch-travis image is built daily but there is this race condition when the image is built right before a new pacman version, then it will break like this until the next image is built.

I have rebuilt the image now, so it should be fixed.

If we see this again I will consider some mitigation for this issue.

**Comment by Teemperor** [comment]
It's fixed, thanks!

Building yay on demand (e.g. when an AUR package was requested) would probably solve it, but the lib names of alpm don't change that often anyway.

**Comment by MrYakobo** [comment]
How would one solve this, except for waiting for a new image? yay is unusable right now for me... :/
