### ISSUE TITLE
Why no `value` in env export ?

### ISSUE THREAD

**Issue by bartoszek** [mikkeloscar/arch-travis#57]
Why dropping `values` when exporting environment variable.
You cant use vars like `TRAVIS_EVENT_TYPE` inside `arch:script` as they lack value...
2e845bb5ebbc689727f2c1454490192897cb7e76 :confused:

**Comment by mikkeloscar** [comment]
docker should pass the value through if the variable is defined in the environment when you execute `docker run`: https://docs.docker.com/engine/reference/commandline/run/#set-environment-variables--e---env---env-file

**Comment by bartoszek** [comment]
Thanks for clarifying.
