### ISSUE TITLE
'Ninja' build broken without masking `LC_ALL`

### ISSUE THREAD

**Issue by bartoszek** [mikkeloscar/arch-travis#59]
Lately all my travis jobs for packages that uses `ninja` build system. Travis logs complains a lot about `/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)`[log](https://api.travis-ci.org/v3/job/562448827/log.txt). Masking `LC_ALL` in `envs` fixes the issue. https://github.com/bartoszek/arch-travis/commit/8054989ec7e293cd4c0881b9e0090532fcd73350

**Comment by mikkeloscar** [comment]
Would you mind making a PR with the fix?
