### ISSUE TITLE
How to copy builded working directory in chroot back to original working directory ?

### ISSUE THREAD

**Issue by frantic1048** [mikkeloscar/arch-travis#6]
I want to use the builded(modified) stuff in Travis, to do some `git commit` , and deploy.

Is there a way to copy builded working directory back to original working directory ?

**Comment by mikkeloscar** [comment]
This is not possible right now, but it sounds like a reasonable feature. I will try to implement something like this later today.

**Comment by mikkeloscar** [comment]
I have added support for this in #7. Rather than copying the build dir, arch-travis will now just bind the build dir to the chroot, thus anything that is build will be in your cwd when arch-travis is done.
