### ISSUE TITLE
arch.script no longer accepts a string

### ISSUE THREAD

**Issue by yan12125** [mikkeloscar/arch-travis#60]
I used to use the following pattern in `.travis.yml` of our projects:
```
arch:
  script: bash ./.ci/build.sh
```
Although undocumented, this worked fine until recently. Now arch-travis raises the following error:
```
-e:1:in `<main>': undefined method `join' for "bash ./.ci/build.sh":String (NoMethodError)`
```
Could you consider to re-allow such an usage? It is supported by the original runner of Travis CI [1]. It is also more natural when there is only one command.

[1] https://docs.travis-ci.com/user/customizing-the-build/

**Comment by bartoszek** [comment]
Haven't though about such use case, thanks for pointing me to this somewhat _obscure issue_ :wink:, I made a patch that checks if `yaml` parser output response to `.join()` and branch evaluation to handle case when parser returns String, and not an Array.

Untill @mikkeloscar merge the PR, you can use my branch in your `.travis.yml`
Just change adres in `curl` invocation to: `https://raw.githubusercontent.com/bartoszek/arch-travis/signle-line-script/arch-travis.sh`

**Comment by yan12125** [comment]
> Just change adres in curl invocation to: https://raw.githubusercontent.com/bartoszek/arch-travis/signle-line-script/arch-travis.sh

Thanks that works well!
