### ISSUE TITLE
Yay - overlapping dependency issue. 

### ISSUE THREAD

**Issue by bartoszek** [mikkeloscar/arch-travis#63]
Yay has a problem with resolving overlapping dependencies in `arch:packages`
**Example** (from [gimp-develop-git](https://travis-ci.org/bartoszek/AUR-gimp-develop-git/builds/584961548)):
```yaml
arch:
  packages:
  - babl-git
  - gegl-git
```
`gegl-git` requires `babl>=0.1.72` which is provided by `babl-git`, but `yay` could not resolve the dependencies without having `babl-git` already installed, those making `yay -S babl-git gegl-git` results in no package being installed.

We could fix it by invoking `yay -S` with single package form `arch:packages` at a time. Or drop `yay` and use `aurutils` as more robust and pristine AUR helper :thinking:

**Comment by mikkeloscar** [comment]
Did you report this to yay? I'm not against changing it if something is better but seems like this is an error they should be aware of and can probably fix?

**Comment by bartoszek** [comment]
Nope, It's outside of scope of the aur helper itself. I've already has this talked through with `yay` developers. They are not willing to expand dependencies resolver outside of `AUR rpc call`. Until `AUR rpc` starts providing solution for dependencies versioning, it's up to the end user to resolve them manually (even `aurman` with it's `deep_search` doesn't resolve versioned dependencies, instead provides `--optimistic_versioning` to mitigate this issue... )

I'll post a PR with sufficient solution for you to review.
