### ISSUE TITLE
Could not resolve host: dash.papyros.io

### ISSUE THREAD

**Issue by fsquillace** [mikkeloscar/arch-travis#72]
Hi,

Thanks for making this. Your sample in README does not seem to work. `papyros.io` does not exist.

`Could not resolve host: dash.papyros.io`

This is the Travis build:
https://travis-ci.org/github/fsquillace/junest/builds/750802344

```
> host dash.papyros.io
Host dash.papyros.io not found: 3(NXDOMAIN)
```

**Comment by bartoszek** [comment]
For the time being you can use my docker image, just edit `.travis.yaml` and replace with `script` with:
```
curl -s https://raw.githubusercontent.com/bartoszek/arch-travis/master/arch-travis.sh| bash
```
It should work fine [[##]](https://travis-ci.org/github/bartoszek)
I'll make a PR and fix this later 😉

**Comment by fsquillace** [comment]
Thanks, that's great! it seems to work.

**Comment by mikkeloscar** [comment]
@bartoszek PR would be welcome :)

**Comment by mikkeloscar** [comment]
This project is no longer maintained.

Travis as a service has degraded significantly in the last years, to a point where I no longer want to waste time on trying to make it work. If anyone is interested to take it over please reach out to me.
