### ISSUE TITLE
Is it working or abandoned repository?

### ISSUE THREAD

**Issue by gustawdaniel** [mikkeloscar/arch-travis#73]

**Comment by mikkeloscar** [comment]
Since travis is no longer that great of a service (very slow) I have personally started to use Github Actions more and more. Because of that I'm not actively maintaining this project. But if someone is interested and can provide fixes (in case it doesn't work) then I will review PRs :)

**Comment by mikkeloscar** [comment]
This project is no longer maintained.

Travis as a service has degraded significantly in the last years, to a point where I no longer want to waste time on trying to make it work. If anyone is interested to take it over please reach out to me.
