### ISSUE TITLE
Use fakechroot to make it work on the container based infrastructure

### ISSUE THREAD

**Issue by FSMaxB** [mikkeloscar/arch-travis#8]
Wouldn't it be possible for arch-travis to run on the container based infrastructure by replacing `chroot` with `fakechroot`? This shouldn't be the default, because a fakechroot might break some stuff compared to a real chroot, but it could be added as a configuration option in the `travis.yml`.

One thing I forgot: You would probably also have to use `fakeroot` to be root inside the chroot. Not sure about that though.

**Comment by mikkeloscar** [comment]
I briefly tried to use fakechroot some time ago, and didn't get it to work (don't remember why). But I would be happy to accept PR's making it work.

**Comment by FSMaxB** [comment]
Ok, great. Maybe I'll find the time for working on this.

**Comment by FSMaxB** [comment]
Seems like I also don't get it to work.

**Comment by mikkeloscar** [comment]
This project is no longer maintained.

Travis as a service has degraded significantly in the last years, to a point where I no longer want to waste time on trying to make it work. If anyone is interested to take it over please reach out to me.
